version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./media:/app/media
      - ./static:/app/static
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data

  celery:
    build: .
    restart: always
    command: celery -A plum_project worker -l info
    volumes:
      - ./models:/app/models
      - ./media:/app/media
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

  celery-beat:
    build: .
    restart: always
    command: celery -A plum_project beat -l info
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data:
  redis_data:
