services:
  - type: web
    name: plum-api
    env: python
    buildCommand: ./build.sh
    startCommand: daphne plum_api.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: plum-db
          property: connectionString
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: true
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://plum-frontend.onrender.com"
      - key: CONFIDENCE_THRESHOLD
        value: 0.7
      - key: IMAGE_SIZE
        value: 320
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ACCESS_TOKEN_LIFETIME_MINUTES
        value: 60
      - key: JWT_REFRESH_TOKEN_LIFETIME_DAYS
        value: 7

  - type: redis
    name: plum-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free

databases:
  - name: plum-db
    plan: free
