# Generated by Django 5.2 on 2025-04-14 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchClassificationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='statut')),
                ('total_images', models.IntegerField(default=0, verbose_name="nombre total d'images")),
                ('processed_images', models.IntegerField(default=0, verbose_name="nombre d'images traitées")),
                ('success_count', models.IntegerField(default=0, verbose_name='nombre de succès')),
                ('error_count', models.IntegerField(default=0, verbose_name="nombre d'erreurs")),
                ('report_file', models.FileField(blank=True, null=True, upload_to='batch_reports/', verbose_name='fichier de rapport')),
            ],
            options={
                'verbose_name': 'tâche de classification par lot',
                'verbose_name_plural': 'tâches de classification par lot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_class', models.CharField(choices=[('bonne_qualite', 'Bonne qualité'), ('non_mure', 'Non mûre'), ('tachetee', 'Tachetée'), ('fissuree', 'Fissurée'), ('meurtrie', 'Meurtrie'), ('pourrie', 'Pourrie')], max_length=20, verbose_name='classe prédite')),
                ('confidence', models.FloatField(verbose_name='confiance')),
                ('is_plum', models.BooleanField(default=True, verbose_name='est une prune')),
                ('prob_bonne_qualite', models.FloatField(default=0.0, verbose_name='probabilité bonne qualité')),
                ('prob_non_mure', models.FloatField(default=0.0, verbose_name='probabilité non mûre')),
                ('prob_tachetee', models.FloatField(default=0.0, verbose_name='probabilité tachetée')),
                ('prob_fissuree', models.FloatField(default=0.0, verbose_name='probabilité fissurée')),
                ('prob_meurtrie', models.FloatField(default=0.0, verbose_name='probabilité meurtrie')),
                ('prob_pourrie', models.FloatField(default=0.0, verbose_name='probabilité pourrie')),
                ('classified_at', models.DateTimeField(auto_now_add=True, verbose_name='date de classification')),
                ('model_version', models.CharField(max_length=50, verbose_name='version du modèle')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='temps de traitement (ms)')),
            ],
            options={
                'verbose_name': 'résultat de classification',
                'verbose_name_plural': 'résultats de classification',
                'ordering': ['-classified_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=50, unique=True, verbose_name='version du modèle')),
                ('deployed_at', models.DateTimeField(auto_now_add=True, verbose_name='date de déploiement')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='précision')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='précision (precision)')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='rappel')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='score F1')),
                ('class_metrics', models.JSONField(blank=True, null=True, verbose_name='métriques par classe')),
                ('confusion_matrix', models.JSONField(blank=True, null=True, verbose_name='matrice de confusion')),
                ('total_predictions', models.IntegerField(default=0, verbose_name='nombre total de prédictions')),
                ('avg_confidence', models.FloatField(blank=True, null=True, verbose_name='confiance moyenne')),
                ('avg_processing_time', models.FloatField(blank=True, null=True, verbose_name='temps de traitement moyen (ms)')),
            ],
            options={
                'verbose_name': 'métriques du modèle',
                'verbose_name_plural': 'métriques du modèle',
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlumImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='plum_images/', verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'upload")),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='lieu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('ground_truth', models.CharField(blank=True, choices=[('bonne_qualite', 'Bonne qualité'), ('non_mure', 'Non mûre'), ('tachetee', 'Tachetée'), ('fissuree', 'Fissurée'), ('meurtrie', 'Meurtrie'), ('pourrie', 'Pourrie')], max_length=20, null=True, verbose_name='vérité terrain')),
            ],
            options={
                'verbose_name': 'image de prune',
                'verbose_name_plural': 'images de prunes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
