# Generated by Django 5.1.3 on 2025-04-17 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_alter_farm_options_alter_user_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("value", models.JSONField(default=dict, verbose_name="valeur")),
                (
                    "metric_type",
                    models.CharField(max_length=50, verbose_name="type de métrique"),
                ),
                (
                    "time_period",
                    models.CharField(
                        default="all", max_length=20, verbose_name="période"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_metrics",
                        to="users.farm",
                        verbose_name="ferme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_metrics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "métrique de dashboard",
                "verbose_name_plural": "métriques de dashboard",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="dashboard_d_user_id_51b6a0_idx"
                    ),
                    models.Index(
                        fields=["farm"], name="dashboard_d_farm_id_fd1bee_idx"
                    ),
                    models.Index(
                        fields=["metric_type"], name="dashboard_d_metric__a78bc4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layout", models.JSONField(default=dict, verbose_name="disposition")),
                (
                    "visible_metrics",
                    models.JSONField(default=list, verbose_name="métriques visibles"),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=300, verbose_name="intervalle de rafraîchissement (s)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "préférence de dashboard",
                "verbose_name_plural": "préférences de dashboard",
                "indexes": [
                    models.Index(fields=["user"], name="dashboard_d_user_id_e37497_idx")
                ],
            },
        ),
    ]
